# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('short_desc', models.CharField(max_length=240)),
                ('instructions', models.TextField()),
                ('duration', models.DurationField()),
                ('url_source', models.URLField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('last_edit', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
