# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='last_edit',
        ),
    ]
