# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20160606_2234'),
        ('reviewsy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='activity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='activity.Activity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='summary',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
